server {
    listen 80;
    server_name _;

    root /srv/materiale/site;
    index index.html;

    charset utf-8;

    location / {
        try_files $uri $uri/ /index.html;
        add_header Cache-Control "no-store";
    }

    location /docs/ {
        alias /srv/materiale/docs/;
        try_files $uri =404;
        add_header Cache-Control "no-store";
    }

    location ~* \.(js|css|json|html)$ {
        try_files $uri =404;
        add_header Cache-Control "no-store";
    }
}
